# If you want to specify explicitly:
image_dir: "/lab/projects/fire_smoke_awr/data/detection/test_sets/early_fire/dev/images/test"
output_dir: "/lab/projects/fire_smoke_awr/outputs/yolo/detection/ABCDE_noEF/EF_dev/experiments/nms/0.5"

# Otherwise you can still use these:
gt_dir: "/lab/projects/fire_smoke_awr/data/detection/test_sets/early_fire/dev"
parent_dir: "/lab/projects/fire_smoke_awr/outputs/yolo/detection/ABCDE_noEF/EF_dev"

model_path: "/lab/projects/fire_smoke_awr/outputs/yolo/detection/ABCDE_noEF/train/weights/best.pt"

intermediate_size: 780
conf_thresh: None
size_thresh: None
nms_iou_thresh: 0.5
postproc: nms   # choices: nms, softnms, wbf, none
save_img: true
